#!/bin/sh

# tell host we are done
echo 1 > /host/.init-done

export PS1='\[\033[01;32m\]\w\[\033[00m\] \$ '
cd /root

if [ -t 0 ] && [ -s /etc/motd ]; then
    eval $(resize)
    if [ $COLUMNS -gt 110 ]; then
        fastfetch --file /etc/motd
    else
        cat /etc/motd
        fastfetch --logo none
    fi
    
fi
