name: Build website

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthonyftwang/minify-action@v1.0.1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: update
            branch: deploy
