name: Build website

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: devatherock/minify-js@v3.0.0
        with:
            add_suffix: false
      - run: git stash; git checkout deploy; git stash apply
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: update
