name: Build website

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: devatherock/minify-js@v3.0.0
        with:
            output: build
            add_suffix: false
      - run: |
          mkdir -p .well-known/matrix
          echo "{\"m.server\":\"{{ secrets.MATRIX_SERVER }}\"}" > .well-known/matrix/server
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build
      - uses: actions/deploy-pages@v4
        id: deployment
