name: Build website

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - run: rsync -avzh . build --exclude .git --exclude .github --exclude build --exclude shell
      
      - uses: nizarmah/auto-minify@v3
        with:
            directory: build
            output: build
            overwrite: true

      - name: Cache C2W layers
        uses: actions/cache@v6
        with:
          path: /tmp/.buildx-cache-c2w
          key: ${{ runner.os }}-cache-c2w

      - name: Cache Image Layers
        uses: actions/cache@v6
        with:
          path: /tmp/.buildx-cache-img
          key: ${{ runner.os }}-cache-img-${{ hashFiles('shell/src/Dockerfile') }}-${{ hashFiles('shell/src/overlay/**') }}

      - env:
          C2W_BUILDX_ARGS: >-
            --extra-flag --cache-from=type=local,src=/tmp/.buildx-cache-c2w
            --extra-flag --cache-to=type=local,dest=/tmp/.buildx-cache-c2w-new,mode=max
          IMG_BUILDX_ARGS: >-
            --cache-from=type=local,src=/tmp/.buildx-cache-img
            --cache-to=type=local,dest=/tmp/.buildx-cache-img-new,mode=max
        run: |
          cd shell
          npm ci
          make -j$(nproc)
          mv build/shell ../build/shell

      - run: |
          rm -rf /tmp/.buildx-cache-c2w /tmp/.buildx-cache-img
          mv /tmp/.buildx-cache-c2w-new /tmp/.buildx-cache-c2w
          mv /tmp/.buildx-cache-img-new /tmp/.buildx-cache-img

      - env:
          MATRIX_SERVER: ${{ secrets.MATRIX_SERVER }}
          MATRIX_HTTP_SERVER: ${{ secrets.MATRIX_HTTP_SERVER }}
        run: |
          sudo mkdir -p build/.well-known/matrix
          echo "{\"m.server\":\"$MATRIX_SERVER\"}" | sudo tee build/.well-known/matrix/server
          sudo tee build/.well-known/matrix/client >/dev/null <<EOF
          {
            "org.matrix.msc3575.proxy": {"url": "$MATRIX_HTTP_SERVER"},
            "m.homeserver": {"base_url": "$MATRIX_HTTP_SERVER"}
          }
          EOF

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - uses: actions/deploy-pages@v4
        id: deployment
