name: Build website

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: nizarmah/auto-minify@v3
        with:
            output: build
            overwrite: true
      - env:
          MATRIX_SERVER: ${{ secrets.MATRIX_SERVER }}
        run: |
          sudo mkdir -p build/.well-known/matrix
          echo "{\"m.server\":\"$MATRIX_SERVER\"}" | sudo tee build/.well-known/matrix/server
          cat << EOF > build/.well-known/client
          {
            "org.matrix.msc3575.proxy": {"url": "$MATRIX_HTTP_SERVER"},
            "m.homeserver": {"base_url": "$MATRIX_HTTP_SERVER"}
          }
          EOF
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build
      - uses: actions/deploy-pages@v4
        id: deployment
